In [22]:
import pandas as pd
import numpy as np

In [2]:
codesignTZ = pd.read_csv('./CoDesign_Projections/TZprojections.csv', thousands = ',')
codesignTZ.head()

,tz16_code,tz16_name,sa2_name16,sa2_main16,sa2_5dig16,sa3_name16,sa3_code16,sa4_name16,sa4_code16,lga_name16,...,ERP_2056,EMP_2016,EMP_2021,EMP_2026,EMP_2031,EMP_2036,EMP_2041,EMP_2046,EMP_2051,EMP_2056
0,1.0,Barangaroo_Headland Park,Sydney - Haymarket - The Rocks,117031337.0,11337.0,Sydney Inner City,11703.0,Sydney - City and Inner South,117.0,Sydney (C),...,1.0,270.0,278.0,279.0,294.0,308.0,324.0,338.0,348.0,358.0
1,2.0,Barangaroo_Northern Cove,Sydney - Haymarket - The Rocks,117031337.0,11337.0,Sydney Inner City,11703.0,Sydney - City and Inner South,117.0,Sydney (C),...,64.0,310.0,666.0,679.0,727.0,778.0,831.0,880.0,923.0,968.0
2,3.0,Barangaroo_Southern Cove,Sydney - Haymarket - The Rocks,117031337.0,11337.0,Sydney Inner City,11703.0,Sydney - City and Inner South,117.0,Sydney (C),...,20.0,126.0,255.0,278.0,296.0,314.0,336.0,360.0,376.0,393.0
3,4.0,Barangaroo_Jenkins Lane,Sydney - Haymarket - The Rocks,117031337.0,11337.0,Sydney Inner City,11703.0,Sydney - City and Inner South,117.0,Sydney (C),...,667.0,3203.0,8561.0,9127.0,9834.0,10940.0,11283.0,11647.0,11846.0,12143.0
4,5.0,Barangaroo_Ferry Terminal,Sydney - Haymarket - The Rocks,117031337.0,11337.0,Sydney Inner City,11703.0,Sydney - City and Inner South,117.0,Sydney (C),...,401.0,7764.0,11249.0,11896.0,12631.0,13331.0,14258.0,15064.0,15694.0,16394.0

In [3]:
codesignTZ['tz16_code'].isnull().sum()

56

In [4]:
print(len(codesignTZ))
codesignTZ = codesignTZ.loc[codesignTZ['tz16_code'].isnull()==False]
print(len(codesignTZ))

2623
2567

In [5]:
codesignTZ.columns

Index(['tz16_code', 'tz16_name', 'sa2_name16', 'sa2_main16', 'sa2_5dig16',
       'sa3_name16', 'sa3_code16', 'sa4_name16', 'sa4_code16', 'lga_name16',
       'lga_code16', 'gcc_name16', 'gcc_code16', 'gsc_distri', 'mb_cat16',
       'albers_ha', 'Metro Stage', 'GIC_AreaName', 'GIC_Precinct_190919',
       'PIFGA_Precinct', 'SGS_CoDBC_UrbanType190924',
       'SGS_CoDBC_Precincts190924', 'SGS_CoDBC_SubPrecinct190924', 'ERP_2016',
       'ERP_2021', 'ERP_2026', 'ERP_2031', 'ERP_2036', 'ERP_2041', 'ERP_2046',
       'ERP_2051', 'ERP_2056', 'EMP_2016', 'EMP_2021', 'EMP_2026', 'EMP_2031',
       'EMP_2036', 'EMP_2041', 'EMP_2046', 'EMP_2051', 'EMP_2056'],
      dtype='object')

In [6]:
len(codesignTZ['SGS_CoDBC_SubPrecinct190924'].unique())

136

In [7]:
codesignSubprecincts = codesignTZ[['SGS_CoDBC_SubPrecinct190924', 'ERP_2016', 'ERP_2056', 'EMP_2016',
                                   'EMP_2056']].groupby('SGS_CoDBC_SubPrecinct190924').sum().reset_index()
print(len(codesignSubprecincts))
codesignSubprecincts = codesignSubprecincts.merge(codesignTZ[['SGS_CoDBC_Precincts190924', 'SGS_CoDBC_SubPrecinct190924']].drop_duplicates(), how='left', on='SGS_CoDBC_SubPrecinct190924')
print(len(codesignSubprecincts))
codesignSubprecincts['ERP_2016'] = codesignSubprecincts['ERP_2016'].astype(int)
codesignSubprecincts['ERP_2056'] = codesignSubprecincts['ERP_2056'].astype(int)
codesignSubprecincts['EMP_2016'] = codesignSubprecincts['EMP_2016'].astype(int)
codesignSubprecincts['EMP_2056'] = codesignSubprecincts['EMP_2056'].astype(int)
codesignSubprecincts.head()

136
136

,SGS_CoDBC_SubPrecinct190924,ERP_2016,ERP_2056,EMP_2016,EMP_2056,SGS_CoDBC_Precincts190924
0,15th Ave,22537,46401,12425,18581,15th Ave
1,Aerotropolis Core,1283,23831,659,58313,Aerotropolis
2,Agriculture and Agribusiness,3464,5541,973,14085,Aerotropolis
3,Alex Avenue,4682,40234,778,2543,NWGA
4,Austral,1312,31562,408,11003,SWGA

In [8]:
print(codesignSubprecincts.loc[codesignSubprecincts['SGS_CoDBC_Precincts190924'].isin(['Aerotropolis', 'SWGA'])].drop('SGS_CoDBC_Precincts190924', axis=1).to_latex(index=False))

\begin{tabular}{lrrrr}
\toprule
  SGS\_CoDBC\_SubPrecinct190924 &  ERP\_2016 &  ERP\_2056 &  EMP\_2016 &  EMP\_2056 \\
\midrule
            Aerotropolis Core &      1283 &     23831 &       659 &     58313 \\
 Agriculture and Agribusiness &      3464 &      5541 &       973 &     14085 \\
                      Austral &      1312 &     31562 &       408 &     11003 \\
               Badgerys Creek &       178 &         0 &        31 &       132 \\
             Catherine Fields &      1643 &      4906 &       519 &      1158 \\
      Catherine Fields (Part) &        77 &     13332 &       158 &      2472 \\
       Catherine Fields North &      1028 &     17058 &       262 &       399 \\
              East Leppington &      1562 &     12383 &       294 &      2003 \\
    Gledswood Hills/The Crest &        17 &      2710 &       137 &       384 \\
                  Kemps Creek &      1363 &       651 &       823 &      6281 \\
             Leppington North &      2445 &     38784 &      1290 &     19084 \\
           Leppington Stage 1 &       316 &     10941 &        97 &       648 \\
        Leppington Stages 2-5 &       355 &     10051 &        91 &       154 \\
         Lowes Creek Maryland &        19 &      2779 &        68 &      1117 \\
                   Mamre Road &       325 &       435 &       424 &     15162 \\
             Northern Gateway &       422 &     17560 &       393 &     22574 \\
                    Oran Park &      5094 &     17626 &       925 &      6464 \\
                  Pondicherry &         8 &     11856 &        37 &       910 \\
                     Rossmore &      2367 &     39128 &       819 &      3169 \\
                  Rossmore SW &       580 &     10542 &       236 &      2200 \\
                  South Creek &       101 &       105 &       299 &      4853 \\
             South Creek West &       524 &     16735 &       129 &      5598 \\
                  Turner Road &      4914 &     18300 &       863 &      8257 \\
                  Twin Creeks &       591 &      1087 &         2 &        14 \\
       Western Sydney Airport &        61 &         3 &         9 &     20225 \\
\bottomrule
\end{tabular}

In [9]:
codesignSubprecincts.to_csv('./CoDesign_Projections/CoDesign_Projections_SubPrecincts.csv', index=False)

In [10]:
codesignLGA = codesignTZ[['lga_name16','ERP_2016',
       'ERP_2021', 'ERP_2026', 'ERP_2031', 'ERP_2036', 'ERP_2041', 'ERP_2046',
       'ERP_2051', 'ERP_2056', 'EMP_2016', 'EMP_2021', 'EMP_2026', 'EMP_2031',
       'EMP_2036', 'EMP_2041', 'EMP_2046', 'EMP_2051', 'EMP_2056']].groupby('lga_name16').sum().reset_index()
#codesignLGA

In [11]:
codesignLGA.to_csv('./CoDesign_Projections/CoDesign_Projections_LGA.csv', index=False)

In [12]:
codesignPrecinct = codesignTZ[['SGS_CoDBC_Precincts190924','ERP_2016',
       'ERP_2021', 'ERP_2026', 'ERP_2031', 'ERP_2036', 'ERP_2041', 'ERP_2046',
       'ERP_2051', 'ERP_2056', 'EMP_2016', 'EMP_2021', 'EMP_2026', 'EMP_2031',
       'EMP_2036', 'EMP_2041', 'EMP_2046', 'EMP_2051', 'EMP_2056']].groupby('SGS_CoDBC_Precincts190924').sum().reset_index()
#codesignPrecinct

In [13]:
codesignPrecinct.to_csv('./CoDesign_Projections/CoDesign_Projections_Precinct.csv', index=False)

In [23]:
codesignLocality = pd.read_csv('CoDesignTZs_WithLocalitySplitAtLGAs.csv')
codesignLocality.head()

,TZ16_CODE,TZ16_NAME,Tz16_Area,TZprojecti,TZprojec_1,TZprojec_2,TZprojec_3,TZprojec_4,TZprojec_5,TZprojec_6,...,TZprojec35,TZprojec36,TZprojec37,TZprojec38,TZprojec39,LOC_PID,NSW_LOCA_2,LGA_CODE16,LGA_NAME16,Split_id
0,665,Concord_Rothwell Park,3.431294e+05,Concord_Rothwell Park,Concord - Mortlake - Cabarita,120011383,11383,Canada Bay,12001,Sydney - Inner West,...,574,641,682,722,763,NSW1012,CONCORD,11520,Canada Bay (A),2
1,702,Concord_Anderson Rd and Brays Rd,8.573758e+05,Concord_Anderson Rd and Brays Rd,Concord - Mortlake - Cabarita,120011383,11383,Canada Bay,12001,Sydney - Inner West,...,739,788,836,881,929,NSW1012,CONCORD,11520,Canada Bay (A),2
2,703,Concord,1.184310e+06,Concord,Concord - Mortlake - Cabarita,120011383,11383,Canada Bay,12001,Sydney - Inner West,...,"1,403","1,487","1,570","1,645","1,729",NSW1012,CONCORD,11520,Canada Bay (A),2
3,704,Bayview Park Ferry Wharf,8.090459e+05,Bayview Park Ferry Wharf,Concord - Mortlake - Cabarita,120011383,11383,Canada Bay,12001,Sydney - Inner West,...,446,466,485,503,522,NSW1012,CONCORD,11520,Canada Bay (A),2
4,705,Concord_Cross St and Wellbank St,5.804393e+05,Concord_Cross St and Wellbank St,Concord - Mortlake - Cabarita,120011383,11383,Canada Bay,12001,Sydney - Inner West,...,375,396,417,437,460,NSW1012,CONCORD,11520,Canada Bay (A),2

In [16]:
codesignLocality = codesignLocality[['TZ16_CODE','NSW_LOCA_2','LGA_NAME16','Split_id']]
codesignLocality.columns = ['tz16_code','Locality','LGA','Split_id']
codesignLocality['Locality'] = codesignLocality['Locality'].str.replace('_','')
print(len(codesignTZ))
codesignLocality = codesignLocality.merge(codesignTZ, how='right', on='tz16_code')
print(len(codesignLocality))
codesignLocality.head()

2567
2567

,tz16_code,Locality,LGA,Split_id,tz16_name,sa2_name16,sa2_main16,sa2_5dig16,sa3_name16,sa3_code16,...,ERP_2056,EMP_2016,EMP_2021,EMP_2026,EMP_2031,EMP_2036,EMP_2041,EMP_2046,EMP_2051,EMP_2056
0,665,CONCORD,Canada Bay (A),2,Concord_Rothwell Park,Concord - Mortlake - Cabarita,120011383.0,11383.0,Canada Bay,12001.0,...,2766.0,281.0,347.0,416.0,522.0,574.0,641.0,682.0,722.0,763.0
1,702,CONCORD,Canada Bay (A),2,Concord_Anderson Rd and Brays Rd,Concord - Mortlake - Cabarita,120011383.0,11383.0,Canada Bay,12001.0,...,4656.0,531.0,600.0,657.0,697.0,739.0,788.0,836.0,881.0,929.0
2,703,CONCORD,Canada Bay (A),2,Concord,Concord - Mortlake - Cabarita,120011383.0,11383.0,Canada Bay,12001.0,...,3102.0,1041.0,1172.0,1267.0,1333.0,1403.0,1487.0,1570.0,1645.0,1729.0
3,704,CONCORD,Canada Bay (A),2,Bayview Park Ferry Wharf,Concord - Mortlake - Cabarita,120011383.0,11383.0,Canada Bay,12001.0,...,2539.0,336.0,387.0,410.0,428.0,446.0,466.0,485.0,503.0,522.0
4,705,CONCORD,Canada Bay (A),2,Concord_Cross St and Wellbank St,Concord - Mortlake - Cabarita,120011383.0,11383.0,Canada Bay,12001.0,...,2882.0,299.0,313.0,340.0,357.0,375.0,396.0,417.0,437.0,460.0

In [18]:
codesignLocality['Locality'].isnull().sum()

0

In [19]:
codesignLocality = codesignLocality[['Locality','LGA','Split_id','ERP_2016',
       'ERP_2056', 'EMP_2016', 'EMP_2056']].groupby(['Locality','LGA','Split_id']).sum().reset_index()
codesignLocality

,Locality,LGA,Split_id,ERP_2016,ERP_2056,EMP_2016,EMP_2056
0,ABBOTSBURY,Fairfield (C),882,6297.0,7102.0,723.0,1087.0
1,ABBOTSFORD,Canada Bay (A),784,5601.0,6849.0,803.0,1354.0
2,ACACIA GARDENS,Blacktown (C),1230,3958.0,5502.0,289.0,721.0
3,AGNES BANKS,Penrith (C),1319,1392.0,1490.0,421.0,508.0
4,AIRDS,Campbelltown (C) (NSW),263,2999.0,5305.0,592.0,906.0
...,...,...,...,...,...,...,...
720,YARRAWARRAH,Sutherland Shire (A),1057,3182.0,3971.0,413.0,669.0
721,YELLOW ROCK,Blue Mountains (C),527,1487.0,1646.0,332.0,381.0
722,YENNORA,Cumberland (A),915,14.0,14.0,3714.0,4274.0
723,YOWIE BAY,Sutherland Shire (A),336,2798.0,3527.0,341.0,509.0
724,ZETLAND,Sydney (C),126,10706.0,22180.0,3396.0,11614.0

In [20]:
codesignLocality['Split_id'].describe()

count     725.000000
mean      686.960000
std       376.955699
min         2.000000
25%       378.000000
50%       675.000000
75%      1025.000000
max      1335.000000
Name: Split_id, dtype: float64

In [21]:
codesignLocality.to_csv('./CoDesign_Projections/CoDesign_Projections_LocalitySplitAtLGAs.csv', index=False)