In [11]:
import pandas as pd
import numpy as np

In [2]:
fidlocalities = pd.read_csv('./ForecastID_Projections/output/ForecastID_Projections_Locality.csv')
fidlocalities.head()

,Area,LGA_fid,2016,2036,2041,LGA
0,Abbotsbury,Fairfield City,4439.0,4581.0,NaN,Fairfield (C)
1,Abbotsford - Wareemba,"Burwood, City of Canada Bay and Strathfield Mu...",7323.0,7325.0,NaN,"Burwood, Canada Bay (A) and Strathfield Munici..."
2,Abbotsford - Wareemba,City of Canada Bay,7323.0,7325.0,NaN,Canada Bay (A)
3,Acacia Gardens - Parklea,Blacktown City,7492.0,7694.0,NaN,Blacktown (C)
4,Airds,Campbelltown City,3082.0,5108.0,NaN,Campbelltown (C) (NSW)

In [12]:
localities = pd.read_csv('LocalitiesSplitAtLGAs.csv')
localities = localities[['Split_id','NSW_LOCA_2','LGA_NAME16']]
localities.head()

   Split_id      NSW_LOCA_2        LGA_NAME16
0         1         CONCORD       Burwood (A)
1         2         CONCORD    Canada Bay (A)
2         3  WOLLSTONECRAFT     Lane Cove (A)
3         4  WOLLSTONECRAFT  North Sydney (A)
4         5          PUTNEY          Ryde (C)

In [18]:
localities.loc[localities[['NSW_LOCA_2','LGA_NAME16']].duplicated(keep=False)].sort_values('NSW_LOCA_2').to_csv('duplicatedLocalities.csv',index=False)

In [4]:
localities['Split_id'].max()

1337

In [5]:
len(localities)

1337

In [6]:
localities['NSW_LOCA_2'] = localities['NSW_LOCA_2'].str.title()
localities['LGA_NAME16'] = localities['LGA_NAME16'].str.title()
fidlocalities['Area'] = fidlocalities['Area'].str.title()
fidlocalities['LGA'] = fidlocalities['LGA'].str.title()

In [7]:
print(len(localities))
localities = localities.merge(fidlocalities, how='left', left_on=['NSW_LOCA_2','LGA_NAME16'], right_on=['Area','LGA'])
print(len(localities))
localities.head()

1337
1337

,Split_id,NSW_LOCA_2,LGA_NAME16,Area,LGA_fid,2016,2036,2041,LGA
0,1,Concord,Burwood (A),NaN,NaN,NaN,NaN,NaN,NaN
1,2,Concord,Canada Bay (A),Concord,City of Canada Bay,15073.0,19156.0,NaN,Canada Bay (A)
2,3,Wollstonecraft,Lane Cove (A),NaN,NaN,NaN,NaN,NaN,NaN
3,4,Wollstonecraft,North Sydney (A),Wollstonecraft,North Sydney Council area,8774.0,9304.0,NaN,North Sydney (A)
4,5,Putney,Ryde (C),NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
localities.isnull().sum()

Split_id         0
NSW_LOCA_2       0
LGA_NAME16       0
Area          1034
LGA_fid       1034
2016          1034
2036          1083
2041          1288
LGA           1034
dtype: int64

In [9]:
1337-1034

303

In [10]:
localities.to_csv('FidGeographiesMatchedToLocalities.csv', index=False)

In [12]:
print(len(fidlocalities))
fidlocalities = fidlocalities.merge(localities, how='left', left_on=['Area','LGA'], right_on = ['NSW_LOCA_2','LGA_NAME16'])
print(len(fidlocalities))

488
488

In [13]:
fidlocalities

,Area_x,LGA_fid_x,2016_x,2036_x,2041_x,LGA_x,Split_id,NSW_LOCA_2,LGA_NAME16,Area_y,LGA_fid_y,2016_y,2036_y,2041_y,LGA_y
0,Abbotsbury,Fairfield City,4439.0,4581.0,NaN,Fairfield (C),882.0,Abbotsbury,Fairfield (C),Abbotsbury,Fairfield City,4439.0,4581.0,NaN,Fairfield (C)
1,Abbotsford - Wareemba,"Burwood, City of Canada Bay and Strathfield Mu...",7323.0,7325.0,NaN,"Burwood, Canada Bay (A) And Strathfield Munici...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Abbotsford - Wareemba,City of Canada Bay,7323.0,7325.0,NaN,Canada Bay (A),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Acacia Gardens - Parklea,Blacktown City,7492.0,7694.0,NaN,Blacktown (C),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Airds,Campbelltown City,3082.0,5108.0,NaN,Campbelltown (C) (Nsw),263.0,Airds,Campbelltown (C) (Nsw),Airds,Campbelltown City,3082.0,5108.0,NaN,Campbelltown (C) (Nsw)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
483,Woronora,Sutherland Shire,2260.0,2243.0,NaN,Sutherland Shire (A),1326.0,Woronora,Sutherland Shire (A),Woronora,Sutherland Shire,2260.0,2243.0,NaN,Sutherland Shire (A)
484,Woronora Heights,Sutherland Shire,2931.0,2753.0,NaN,Sutherland Shire (A),1019.0,Woronora Heights,Sutherland Shire (A),Woronora Heights,Sutherland Shire,2931.0,2753.0,NaN,Sutherland Shire (A)
485,Yagoona,City of Canterbury Bankstown,18736.0,23100.0,NaN,Canterbury-Bankstown (A),551.0,Yagoona,Canterbury-Bankstown (A),Yagoona,City of Canterbury Bankstown,18736.0,23100.0,NaN,Canterbury-Bankstown (A)
486,Yarrawarrah,Sutherland Shire,2831.0,2721.0,NaN,Sutherland Shire (A),1057.0,Yarrawarrah,Sutherland Shire (A),Yarrawarrah,Sutherland Shire,2831.0,2721.0,NaN,Sutherland Shire (A)
487,Yowie Bay,Sutherland Shire,3066.0,3058.0,NaN,Sutherland Shire (A),336.0,Yowie Bay,Sutherland Shire (A),Yowie Bay,Sutherland Shire,3066.0,3058.0,NaN,Sutherland Shire (A)

In [14]:
fidlocalities.isnull().sum()

Area_x          0
LGA_fid_x       0
2016_x          0
2036_x         84
2041_x        404
LGA_x           0
Split_id      185
NSW_LOCA_2    185
LGA_NAME16    185
Area_y        185
LGA_fid_y     185
2016_y        185
2036_y        234
2041_y        439
LGA_y         185
dtype: int64

Out of 488, 185 were not matched