In [1]:
import pandas as pd
import numpy as np

In [2]:
codesignTZ = pd.read_csv('./CoDesign_Projections/TZprojections.csv', thousands = ',')
codesignTZ.head()

,tz16_code,tz16_name,sa2_name16,sa2_main16,sa2_5dig16,sa3_name16,sa3_code16,sa4_name16,sa4_code16,lga_name16,...,ERP_2056,EMP_2016,EMP_2021,EMP_2026,EMP_2031,EMP_2036,EMP_2041,EMP_2046,EMP_2051,EMP_2056
0,1.0,Barangaroo_Headland Park,Sydney - Haymarket - The Rocks,117031337.0,11337.0,Sydney Inner City,11703.0,Sydney - City and Inner South,117.0,Sydney (C),...,1.0,270.0,278.0,279.0,294.0,308.0,324.0,338.0,348.0,358.0
1,2.0,Barangaroo_Northern Cove,Sydney - Haymarket - The Rocks,117031337.0,11337.0,Sydney Inner City,11703.0,Sydney - City and Inner South,117.0,Sydney (C),...,64.0,310.0,666.0,679.0,727.0,778.0,831.0,880.0,923.0,968.0
2,3.0,Barangaroo_Southern Cove,Sydney - Haymarket - The Rocks,117031337.0,11337.0,Sydney Inner City,11703.0,Sydney - City and Inner South,117.0,Sydney (C),...,20.0,126.0,255.0,278.0,296.0,314.0,336.0,360.0,376.0,393.0
3,4.0,Barangaroo_Jenkins Lane,Sydney - Haymarket - The Rocks,117031337.0,11337.0,Sydney Inner City,11703.0,Sydney - City and Inner South,117.0,Sydney (C),...,667.0,3203.0,8561.0,9127.0,9834.0,10940.0,11283.0,11647.0,11846.0,12143.0
4,5.0,Barangaroo_Ferry Terminal,Sydney - Haymarket - The Rocks,117031337.0,11337.0,Sydney Inner City,11703.0,Sydney - City and Inner South,117.0,Sydney (C),...,401.0,7764.0,11249.0,11896.0,12631.0,13331.0,14258.0,15064.0,15694.0,16394.0

In [3]:
codesignTZ['tz16_code'].isnull().sum()

56

In [4]:
print(len(codesignTZ))
codesignTZ = codesignTZ.loc[codesignTZ['tz16_code'].isnull()==False]
print(len(codesignTZ))

2623
2567

In [5]:
codesignTZ.columns

Index(['tz16_code', 'tz16_name', 'sa2_name16', 'sa2_main16', 'sa2_5dig16',
       'sa3_name16', 'sa3_code16', 'sa4_name16', 'sa4_code16', 'lga_name16',
       'lga_code16', 'gcc_name16', 'gcc_code16', 'gsc_distri', 'mb_cat16',
       'albers_ha', 'Metro Stage', 'GIC_AreaName', 'GIC_Precinct_190919',
       'PIFGA_Precinct', 'SGS_CoDBC_UrbanType190924',
       'SGS_CoDBC_Precincts190924', 'SGS_CoDBC_SubPrecinct190924', 'ERP_2016',
       'ERP_2021', 'ERP_2026', 'ERP_2031', 'ERP_2036', 'ERP_2041', 'ERP_2046',
       'ERP_2051', 'ERP_2056', 'EMP_2016', 'EMP_2021', 'EMP_2026', 'EMP_2031',
       'EMP_2036', 'EMP_2041', 'EMP_2046', 'EMP_2051', 'EMP_2056'],
      dtype='object')

In [6]:
codesignTZ = codesignTZ[['tz16_code', 'tz16_name','lga_code16','lga_name16','gsc_distri', 'GIC_AreaName', 'GIC_Precinct_190919','SGS_CoDBC_UrbanType190924','SGS_CoDBC_Precincts190924','ERP_2016', 'ERP_2056', 'EMP_2016', 'EMP_2056']]
codesignTZ.head()

,tz16_code,tz16_name,lga_code16,lga_name16,gsc_distri,GIC_AreaName,GIC_Precinct_190919,SGS_CoDBC_UrbanType190924,SGS_CoDBC_Precincts190924,ERP_2016,ERP_2056,EMP_2016,EMP_2056
0,1.0,Barangaroo_Headland Park,17200.0,Sydney (C),Central,OutWSPP,OutWSPP,OutWSPP,OutWSPP,1.0,1.0,270.0,358.0
1,2.0,Barangaroo_Northern Cove,17200.0,Sydney (C),Central,OutWSPP,OutWSPP,OutWSPP,OutWSPP,1.0,64.0,310.0,968.0
2,3.0,Barangaroo_Southern Cove,17200.0,Sydney (C),Central,OutWSPP,OutWSPP,OutWSPP,OutWSPP,1.0,20.0,126.0,393.0
3,4.0,Barangaroo_Jenkins Lane,17200.0,Sydney (C),Central,OutWSPP,OutWSPP,OutWSPP,OutWSPP,58.0,667.0,3203.0,12143.0
4,5.0,Barangaroo_Ferry Terminal,17200.0,Sydney (C),Central,OutWSPP,OutWSPP,OutWSPP,OutWSPP,141.0,401.0,7764.0,16394.0

## Densities

In [7]:
tzareas = pd.read_csv('./TPA_SPATIAL_TZ_NSW_2016_SHP/TZ_NSW_2016.csv')
tzareas.head()

   TZ16_CODE     TZ16_NAME     Tz16_Area
0       7180    Mongarlowe  1.538767e+09
1       7181     Braidwood  2.345105e+08
2       7182  Majors Creek  1.643683e+09
3       7185       Karabar  6.978598e+06
4       7188    Queanbeyan  4.760921e+06

In [8]:
tzareas['Tz16_Area'].describe() # m2

count    3.758000e+03
mean     2.130485e+08
std      2.770088e+09
min      4.123152e+03
25%      4.417714e+05
50%      1.020593e+06
75%      4.088608e+06
max      1.466857e+11
Name: Tz16_Area, dtype: float64

In [9]:
# Get TZ area (m.sq)

print(len(codesignTZ))
codesignTZ = codesignTZ.merge(tzareas[['TZ16_CODE','Tz16_Area']], how='left', left_on='tz16_code', right_on='TZ16_CODE').drop('TZ16_CODE', axis=1)
print(len(codesignTZ))

2567
2567

In [11]:
codesignTZ.isnull().sum()

tz16_code                    0
tz16_name                    0
lga_code16                   0
lga_name16                   0
gsc_distri                   1
GIC_AreaName                 0
GIC_Precinct_190919          0
SGS_CoDBC_UrbanType190924    0
SGS_CoDBC_Precincts190924    0
ERP_2016                     0
ERP_2056                     0
EMP_2016                     0
EMP_2056                     0
Tz16_Area                    0
dtype: int64

In [14]:
# Density (per km.sq.)

codesignTZ['PopDensity_2016'] = codesignTZ['ERP_2016']*(10**6)/codesignTZ['Tz16_Area']
codesignTZ['PopDensity_2056'] = codesignTZ['ERP_2056']*(10**6)/codesignTZ['Tz16_Area']
codesignTZ['EmpDensity_2016'] = codesignTZ['EMP_2016']*(10**6)/codesignTZ['Tz16_Area']
codesignTZ['EmpDensity_2056'] = codesignTZ['EMP_2056']*(10**6)/codesignTZ['Tz16_Area']
codesignTZ['PopDensity_Diff'] = codesignTZ['PopDensity_2056']-codesignTZ['PopDensity_2016']
codesignTZ['EmpDensity_Diff'] = codesignTZ['EmpDensity_2056']-codesignTZ['EmpDensity_2016']
codesignTZ.head()

,tz16_code,tz16_name,lga_code16,lga_name16,gsc_distri,GIC_AreaName,GIC_Precinct_190919,SGS_CoDBC_UrbanType190924,SGS_CoDBC_Precincts190924,ERP_2016,ERP_2056,EMP_2016,EMP_2056,Tz16_Area,PopDensity_2016,PopDensity_2056,EmpDensity_2016,EmpDensity_2056,PopDensity_Diff,EmpDensity_Diff
0,1.0,Barangaroo_Headland Park,17200.0,Sydney (C),Central,OutWSPP,OutWSPP,OutWSPP,OutWSPP,1.0,1.0,270.0,358.0,64884.126263,15.412090,15.412090,4161.264327,5517.528256,0.000000,1356.263929
1,2.0,Barangaroo_Northern Cove,17200.0,Sydney (C),Central,OutWSPP,OutWSPP,OutWSPP,OutWSPP,1.0,64.0,310.0,968.0,74488.645912,13.424865,859.191347,4161.708086,12995.269120,845.766482,8833.561034
2,3.0,Barangaroo_Southern Cove,17200.0,Sydney (C),Central,OutWSPP,OutWSPP,OutWSPP,OutWSPP,1.0,20.0,126.0,393.0,30794.773994,32.473042,649.460847,4091.603336,12761.905643,616.987805,8670.302307
3,4.0,Barangaroo_Jenkins Lane,17200.0,Sydney (C),Central,OutWSPP,OutWSPP,OutWSPP,OutWSPP,58.0,667.0,3203.0,12143.0,13964.450131,4153.403783,47764.143501,229368.143381,869565.209203,43610.739719,640197.065822
4,5.0,Barangaroo_Ferry Terminal,17200.0,Sydney (C),Central,OutWSPP,OutWSPP,OutWSPP,OutWSPP,141.0,401.0,7764.0,16394.0,33804.091232,4171.092754,11862.469464,229676.341443,484970.883774,7691.376710,255294.542331

In [15]:
codesignTZ.to_csv('TZ_Densities.csv', index=False)

In [16]:
codesignTZ.describe()

,tz16_code,lga_code16,ERP_2016,ERP_2056,EMP_2016,EMP_2056,Tz16_Area,PopDensity_2016,PopDensity_2056,EmpDensity_2016,EmpDensity_2056,PopDensity_Diff,EmpDensity_Diff
count,2567.000000,2567.000000,2567.000000,2567.000000,2567.000000,2567.000000,2.567000e+03,2567.000000,2567.000000,2567.000000,2567.000000,2567.000000,2567.000000
mean,2278.680171,14677.012076,1826.359953,3218.155434,970.673549,1671.612778,4.155807e+06,4358.492166,7914.237795,11843.431876,18824.862346,3555.745629,6981.430471
std,1489.853811,2446.320553,1317.675173,2426.709635,1539.729935,2638.232578,6.195884e+07,7833.751290,13736.085042,48710.628738,76096.762241,9075.183355,29291.112519
min,1.000000,10750.000000,0.000000,0.000000,0.000000,0.000000,4.123152e+03,0.000000,0.000000,0.000000,0.000000,-12982.992118,-54.533524
25%,1004.500000,12380.000000,611.000000,1560.000000,207.000000,370.000000,2.938061e+05,729.119663,2005.000563,220.299697,405.544625,430.357925,143.043080
50%,2145.000000,14900.000000,1828.000000,3089.000000,422.000000,759.000000,6.619008e+05,2894.952919,4474.913814,588.619008,1039.787369,1270.097113,414.635247
75%,3626.500000,17100.000000,2791.000000,4492.000000,926.500000,1659.500000,1.231672e+06,4841.000748,8488.227884,2437.866469,3845.037189,3030.135421,1398.557924
max,5025.000000,18500.000000,6355.000000,26405.000000,14095.000000,41841.000000,2.452672e+09,183197.294479,193974.268067,520986.849168,869565.209203,179865.575508,640197.065822